# Generated by Django 3.0.7 on 2020-07-05 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='socialtoken',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='socialtoken',
            name='app',
        ),
    ]
